# Site settings
title:          "The Dilettante"
description:    "A bragging zone of Nguyên"
url:            "https://baonguyenx.github.io"

# Author
author:
  name:         "Jay Nguyễn"
  email:        "entrep.baonguyen@gmail.com"

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
